"""Money as an integer count of minor units.

Float is disqualified, not discouraged: `0.1 + 0.2 != 0.3` in IEEE-754, and the
boundaries where that bites are exactly the boundaries this engine tests.
`Decimal` is exact but carries hidden context state (precision, rounding mode,
trailing-zero significance) which is a source of non-reproducibility. An `int`
hashes, compares bit-exactly, serialises losslessly, and stores as BIGINT.

PKR's ISO 4217 exponent is 2, so one minor unit is one paisa. Pakistani wallet
receipts are effectively always whole rupees, but that is data, not a schema:
everything normalises to paisa.

`Decimal` appears exactly once in this module — inside `from_major`, at the
parsing boundary — and never escapes it.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import ROUND_HALF_UP, Decimal, InvalidOperation

__all__ = ["DEFAULT_CURRENCY", "MINOR_EXPONENT", "Money"]

# ISO 4217 minor-unit exponents. Extend deliberately; a missing currency should
# raise rather than silently assume 2.
MINOR_EXPONENT: dict[str, int] = {"PKR": 2}

DEFAULT_CURRENCY = "PKR"


@dataclass(frozen=True, slots=True, order=True)
class Money:
    """An exact amount, stored as `minor` units of `currency`.

    Ordering is generated by the dataclass and compares `minor` first. It is
    only meaningful within a single currency; this system is single-currency by
    construction, and arithmetic (which is where a mixed-currency bug would
    actually cost money) is guarded.
    """

    minor: int
    currency: str = DEFAULT_CURRENCY

    def __post_init__(self) -> None:
        # bool is an int subclass; Money(True) would be a silent 1 paisa.
        if not isinstance(self.minor, int) or isinstance(self.minor, bool):
            raise TypeError("Money.minor must be int (never float/Decimal/bool)")
        if self.currency not in MINOR_EXPONENT:
            raise ValueError(f"unknown currency {self.currency!r}")

    @classmethod
    def zero(cls, currency: str = DEFAULT_CURRENCY) -> Money:
        return cls(0, currency)

    @classmethod
    def from_major(cls, major: str | Decimal | int, currency: str = DEFAULT_CURRENCY) -> Money:
        """Build from a major-unit value (rupees) at the parsing boundary.

        Accepts `str`, `Decimal` or `int`. `float` is rejected outright: by the
        time a float exists the precision is already gone, and accepting one
        would legitimise the very representation this class exists to forbid.
        Half-up rounding is the retail convention and matches receipt printing.
        """
        if isinstance(major, float):
            raise TypeError("Money.from_major refuses float; pass str/Decimal/int")
        if isinstance(major, bool):
            raise TypeError("Money.from_major refuses bool")
        exp = MINOR_EXPONENT[currency]
        try:
            d = Decimal(str(major))
        except InvalidOperation as e:
            raise ValueError(f"unparseable amount {major!r}") from e
        if not d.is_finite():
            raise ValueError(f"non-finite amount {major!r}")
        q = d.quantize(Decimal(1).scaleb(-exp), rounding=ROUND_HALF_UP)
        return cls(int(q.scaleb(exp)), currency)

    def __add__(self, other: Money) -> Money:
        self._same_currency(other)
        return Money(self.minor + other.minor, self.currency)

    def __sub__(self, other: Money) -> Money:
        self._same_currency(other)
        return Money(self.minor - other.minor, self.currency)

    def __neg__(self) -> Money:
        return Money(-self.minor, self.currency)

    def __abs__(self) -> Money:
        return Money(abs(self.minor), self.currency)

    def _same_currency(self, other: Money) -> None:
        if not isinstance(other, Money):
            raise TypeError(f"expected Money, got {type(other).__name__}")
        if self.currency != other.currency:
            raise ValueError(f"currency mismatch {self.currency}/{other.currency}")

    @property
    def as_major_str(self) -> str:
        """Display form, e.g. `1500.00`. Never feed this back into arithmetic."""
        exp = MINOR_EXPONENT[self.currency]
        return f"{Decimal(self.minor).scaleb(-exp):.{exp}f}"

    def __str__(self) -> str:
        return f"{self.currency} {self.as_major_str}"
