/**
 * API client, with a mock mode so the whole app runs with no backend.
 *
 * Toggle with `VITE_USE_MOCKS` in `.env.local` (defaults to mocks ON, so a fresh
 * clone runs immediately). Set it to `false` once you want to hit the real API:
 *
 *     VITE_USE_MOCKS=false npm run dev
 *
 * The mock payloads in `src/mocks/` are NOT hand-written — they are generated by
 * running the real verification engine (`scripts/generate_api_mocks.py`). So a UI
 * that renders them correctly will render the live API correctly too.
 */

import dashboardMock from '../mocks/dashboard.json'
import verificationsMock from '../mocks/verifications.json'
import type { DashboardSummary, VerificationList, VerificationResult } from '../types'

const USE_MOCKS = import.meta.env.VITE_USE_MOCKS !== 'false'

const TOKEN_KEY = 'proofpay.token'

/** Pretend the network took a moment, so loading states are visible in mock mode. */
const latency = (ms = 250) => new Promise((r) => setTimeout(r, ms))

export function getToken(): string | null {
  try {
    return localStorage.getItem(TOKEN_KEY)
  } catch {
    return null
  }
}

function setToken(token: string | null): void {
  try {
    if (token) localStorage.setItem(TOKEN_KEY, token)
    else localStorage.removeItem(TOKEN_KEY)
  } catch {
    /* private browsing — sign-in simply won't persist across reloads */
  }
}

export function logout(): void {
  setToken(null)
}

async function request<T>(path: string): Promise<T> {
  const token = getToken()
  const res = await fetch(`/api/v1${path}`, {
    headers: token ? { Authorization: `Bearer ${token}` } : {},
  })

  if (res.status === 401) {
    setToken(null)
    throw new Error('Session expired — please sign in again.')
  }
  if (!res.ok) {
    throw new Error(`${res.status} ${res.statusText}`)
  }
  return res.json() as Promise<T>
}

/**
 * Sign in.
 *
 * The stub backend accepts ANY password; the username selects the role —
 * `owner` (admin), `manager`, `rider`, `reviewer`. Use `owner` unless you are
 * specifically working on the scoped-access screens.
 */
export async function login(username: string, password: string): Promise<void> {
  if (USE_MOCKS) {
    await latency(150)
    setToken('mock-token')
    return
  }

  // OAuth2 password flow: form-encoded, not JSON.
  const res = await fetch('/api/v1/auth/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ username, password }),
  })
  if (!res.ok) throw new Error('Sign-in failed')

  const { access_token } = (await res.json()) as { access_token: string }
  setToken(access_token)
}

export async function listVerifications(): Promise<VerificationList> {
  if (USE_MOCKS) {
    await latency()
    return verificationsMock as unknown as VerificationList
  }
  return request<VerificationList>('/verifications')
}

export async function getVerification(id: string): Promise<VerificationResult> {
  if (USE_MOCKS) {
    await latency()
    const list = verificationsMock as unknown as VerificationList
    const found = list.items.find((v) => v.id === id)
    if (!found) throw new Error(`No such verification: ${id}`)
    return found
  }
  return request<VerificationResult>(`/verifications/${id}`)
}

export async function getDashboard(): Promise<DashboardSummary> {
  if (USE_MOCKS) {
    await latency()
    return dashboardMock as DashboardSummary
  }
  return request<DashboardSummary>('/dashboard/summary')
}

export const usingMocks = USE_MOCKS
