/**
 * The API client. Two modes, one surface.
 *
 *   MOCKS (default)  `src/mocks/*.json`, generated by running the real engine
 *                    (`scripts/generate_api_mocks.py`). The app runs with no
 *                    backend, no network and no venue wifi, which is the only
 *                    reason a live demo is safe to give.
 *   LIVE             `VITE_USE_MOCKS=false`. Signs in, holds a Bearer token, and
 *                    talks to `/api/v1` through the dev-server proxy.
 *
 *     VITE_USE_MOCKS=false npm run dev
 *
 * Both modes return the SAME shapes, because every response — mock included —
 * goes through `src/api/adapt.ts`. See the note at the top of that file.
 *
 * Sign-in is automatic and silent. The demo backend issues a token for any
 * password and picks the role from the username, so there is no login screen to
 * fail on stage: the first request that needs a token fetches one.
 */

import { adaptDashboard, adaptSummaries, adaptVerification } from './adapt'
import dashboardMock from '../mocks/dashboard.json'
import verificationsMock from '../mocks/verifications.json'
import type { DashboardSummary, VerificationResult, VerificationSummary } from '../types'

const USE_MOCKS = import.meta.env.VITE_USE_MOCKS !== 'false'

const API_BASE = '/api/v1'
const TOKEN_KEY = 'proofpay.token'

/**
 * The demo principal. `owner` is the merchant admin — the shopkeeper whose phone
 * this is. The stub backend accepts ANY password and reads the role off the
 * username, so this pair is the whole of authentication until real accounts land.
 */
const DEMO_USERNAME = 'owner'
const DEMO_PASSWORD = 'proofpay-demo'

/**
 * The order a screenshot is checked against.
 *
 * `POST /verifications` wants one, and this build has no order picker yet, so the
 * live path asks the API for the merchant's current order rather than inventing a
 * reference. The fallback is the demo backend's own order id — a real row on that
 * server, not a number made up to fill a field.
 */
const FALLBACK_ORDER_ID = 'order_demo_1001'

/** Pretend the network took a moment, so loading states are visible in mock mode. */
const latency = (ms = 250): Promise<void> => new Promise((r) => setTimeout(r, ms))

/* ── the token ─────────────────────────────────────────────────────────────── */

function readToken(): string | null {
  try {
    return localStorage.getItem(TOKEN_KEY)
  } catch {
    return null // private browsing — the token simply will not persist
  }
}

function writeToken(token: string | null): void {
  try {
    if (token) localStorage.setItem(TOKEN_KEY, token)
    else localStorage.removeItem(TOKEN_KEY)
  } catch {
    /* nothing to do: the in-flight request still carries the token */
  }
}

/** In flight, so a burst of first requests triggers exactly one sign-in. */
let tokenRequest: Promise<string> | null = null

/** POST /api/v1/auth/token — form-encoded, per OAuth2's password flow. */
async function fetchToken(): Promise<string> {
  const res = await fetch(`${API_BASE}/auth/token`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      grant_type: 'password',
      username: DEMO_USERNAME,
      password: DEMO_PASSWORD,
    }),
  })
  if (!res.ok) throw new Error('Could not sign in to ProofPay.')

  const body = (await res.json()) as { access_token?: unknown }
  const token = typeof body.access_token === 'string' ? body.access_token : null
  if (!token) throw new Error('Sign-in returned no token.')
  return token
}

function ensureToken(): Promise<string> {
  const cached = readToken()
  if (cached !== null) return Promise.resolve(cached)

  tokenRequest ??= fetchToken()
    .then((token) => {
      writeToken(token)
      return token
    })
    .finally(() => {
      tokenRequest = null
    })

  return tokenRequest
}

function forgetToken(): void {
  writeToken(null)
  tokenRequest = null
}

/* ── requests ──────────────────────────────────────────────────────────────── */

/**
 * The error envelope is `{ code, message }`. Read the message when there is one —
 * "Only JPEG, PNG, and WebP images are accepted" is worth showing the merchant,
 * and `415 Unsupported Media Type` is not.
 */
async function failure(res: Response): Promise<Error> {
  try {
    const body = (await res.json()) as { message?: unknown; detail?: unknown }
    const message = typeof body.message === 'string' ? body.message : body.detail
    if (typeof message === 'string' && message.trim() !== '') return new Error(message)
  } catch {
    /* not JSON — fall through to the status line */
  }
  return new Error(`${res.status} ${res.statusText}`.trim())
}

/**
 * One authenticated call. A 401 means the token we held is stale, which happens
 * whenever the backend restarts mid-demo: drop it, sign in again, and retry once.
 */
async function request(path: string, init: RequestInit = {}, retry = true): Promise<unknown> {
  const token = await ensureToken()
  const headers = new Headers(init.headers)
  headers.set('Authorization', `Bearer ${token}`)

  const res = await fetch(`${API_BASE}${path}`, { ...init, headers })

  if (res.status === 401 && retry) {
    forgetToken()
    return request(path, init, false)
  }
  if (!res.ok) throw await failure(res)
  return res.json()
}

/* ── the mock fixtures ─────────────────────────────────────────────────────── */

function rawFixtures(): unknown[] {
  const items = (verificationsMock as { items?: unknown }).items
  return Array.isArray(items) ? items : []
}

function rawFixture(id: string): unknown {
  return rawFixtures().find((item) => (item as { id?: unknown }).id === id) ?? null
}

/**
 * Every fixture we can read. Order is the file's own — the demo rail sorts for
 * itself in `App.tsx`, and the API layer has no business knowing which verdict
 * is the worst one.
 */
function fixtures(): VerificationResult[] {
  const out: VerificationResult[] = []
  for (const raw of rawFixtures()) {
    try {
      out.push(adaptVerification(raw))
    } catch {
      /* a fixture we cannot read is one we must not show */
    }
  }
  return out
}

/* ── the calls ─────────────────────────────────────────────────────────────── */

export async function listVerifications(): Promise<VerificationSummary[]> {
  if (USE_MOCKS) {
    await latency()
    return adaptSummaries(verificationsMock)
  }
  return adaptSummaries(await request('/verifications'))
}

export async function getVerification(id: string): Promise<VerificationResult> {
  if (USE_MOCKS) {
    await latency()
    const raw = rawFixture(id)
    if (raw === null) throw new Error(`No such verification: ${id}`)
    return adaptVerification(raw)
  }
  return adaptVerification(await request(`/verifications/${encodeURIComponent(id)}`))
}

export async function getDashboard(): Promise<DashboardSummary> {
  if (USE_MOCKS) {
    await latency()
    return adaptDashboard(dashboardMock)
  }
  return adaptDashboard(await request('/dashboard/summary'))
}

/** Idempotency-Key: the same screenshot submitted twice must not become two checks. */
function idempotencyKey(): string {
  try {
    return crypto.randomUUID()
  } catch {
    return `pp-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`
  }
}

let orderId: string | null = null

/** The merchant's current order, asked for once and remembered. */
async function currentOrderId(): Promise<string> {
  if (orderId !== null) return orderId
  try {
    const body = await request('/orders')
    const items = (body as { items?: unknown }).items
    const first = Array.isArray(items) ? (items[0] as { id?: unknown } | undefined) : undefined
    orderId = typeof first?.id === 'string' ? first.id : FALLBACK_ORDER_ID
  } catch {
    orderId = FALLBACK_ORDER_ID
  }
  return orderId
}

/**
 * Hand a customer's screenshot to the engine.
 *
 * LIVE: multipart, with the order it is being checked against and an idempotency
 * key. The backend rejects anything that is not JPEG, PNG or WebP and anything
 * over 10 MB, and those messages are written for the merchant, so they are shown
 * as they come.
 *
 * MOCKS: there is nothing to read the screenshot WITH, so the file is not
 * inspected and a fixture is replayed. This is the one place mock mode is not the
 * truth, and it is why the demo rail exists — those buttons name the verdict they
 * are about to show instead of pretending to have read a picture.
 *
 * The replay is the VERIFIED fixture, and that is a considered choice. The rail
 * already reaches the three verdicts that say no; VERIFIED is the fourth, it is
 * what most payments actually are, and it is the ONLY screen carrying "Use it" —
 * the memory that catches the same genuine receipt arriving twice. Without it
 * here, half the product is unreachable with no backend running.
 */
export async function submitClaim(file: File): Promise<VerificationResult> {
  if (USE_MOCKS) {
    await latency(400)
    const all = fixtures()
    const replay = all.find((v) => v.status === 'VERIFIED') ?? all[0]
    if (!replay) throw new Error('No verification to show yet.')
    return replay
  }

  const body = new FormData()
  body.append('order_id', await currentOrderId())
  body.append('screenshot', file, file.name)

  return adaptVerification(
    await request('/verifications', {
      method: 'POST',
      body,
      headers: { 'Idempotency-Key': idempotencyKey() },
    }),
  )
}

/**
 * Put the demo back to a clean slate.
 *
 * Best-effort and deliberately silent: the reset control is the thing that has to
 * work when everything else has not, so a backend that is down must not stop the
 * screen from clearing. In mock mode there is no server state to clear.
 */
export async function resetDemo(): Promise<void> {
  if (USE_MOCKS) return
  try {
    await request('/demo/reset', { method: 'POST' })
  } catch {
    /* the screen still resets; that is the part the merchant can see */
  }
}
