"""Atomic local filesystem implementation of the proof blob store."""

from __future__ import annotations

import hashlib
import os
import tempfile
from pathlib import Path

from .base import StoredObject
from .errors import StorageError


class LocalStorage:
    """Store private proof objects below one configured directory.

    Keys are generated by :func:`validate_image`, but this class still checks
    them so a future caller cannot turn a storage key into path traversal.
    Writes use a same-directory temporary file followed by ``os.replace``;
    readers therefore see either the old complete object or the new complete
    object, never a partially written upload.
    """

    def __init__(self, root: str | os.PathLike[str]):
        self.root = Path(root).expanduser()
        try:
            self.root.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            raise StorageError("Could not initialise the configured proof store") from exc

    def _path_for(self, key: str) -> Path:
        candidate = Path(key)
        if not key or candidate.is_absolute() or ".." in candidate.parts:
            raise StorageError("Storage keys must be relative and traversal-free")
        path = self.root / candidate
        try:
            path.relative_to(self.root)
        except ValueError as exc:  # defensive for platform-specific paths
            raise StorageError("Storage key escapes the configured root") from exc
        return path

    def put(self, key: str, content: bytes) -> StoredObject:
        """Atomically write ``content`` at ``key`` and return its metadata."""

        path = self._path_for(key)
        temporary_name: str | None = None
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            with tempfile.NamedTemporaryFile(
                mode="wb", dir=path.parent, prefix=".proofpay-", delete=False
            ) as temporary:
                temporary_name = temporary.name
                temporary.write(content)
                temporary.flush()
                os.fsync(temporary.fileno())
            os.replace(temporary_name, path)
        except OSError as exc:
            if temporary_name is not None:
                try:
                    os.unlink(temporary_name)
                except OSError:
                    pass
            raise StorageError(f"Could not store proof object {key}") from exc

        return StoredObject(
            key=key,
            byte_size=len(content),
            sha256=hashlib.sha256(content).hexdigest(),
        )

    def get(self, key: str) -> bytes:
        """Read one stored object."""

        path = self._path_for(key)
        try:
            return path.read_bytes()
        except OSError as exc:
            raise StorageError(f"Could not read proof object {key}") from exc

    def delete(self, key: str) -> None:
        """Delete one object, treating an already absent object as success."""

        path = self._path_for(key)
        try:
            path.unlink(missing_ok=True)
        except OSError as exc:
            raise StorageError(f"Could not delete proof object {key}") from exc


__all__ = ["LocalStorage", "StoredObject"]
