"""Receipt Image Tampering & Compression Pipeline.

WHY THIS FILE EXISTS:
    The PNGs generated by Playwright are 100% vector-perfect, but real receipt
    screenshots uploaded to ProofPay are:
      1. Compressed by WhatsApp (JPEG artifacts)
      2. For SUSPICIOUS cases, potentially digitally altered.

    This script processes the pristine PNGs in fixtures/demo/images/:
      - Applies WhatsApp-grade JPEG compression to ALL images.
      - Injects forensic artifacts (splicing edges, double-compression noise)
        into the SUSPICIOUS cases (S01-S06) so the Phase 3 Tamper Detector
        has something realistic to find.

    Note: The text itself was already tampered in HTML (for OCR extraction),
    so here we just inject the visual *traces* of the crime around the text.
"""

import json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFilter
import random

# ── Paths ──────────────────────────────────────────────────────────
REPO_ROOT = Path(__file__).resolve().parents[1]
IMAGES_DIR = REPO_ROOT / "fixtures" / "demo" / "images"
MANIFEST_PATH = REPO_ROOT / "fixtures" / "demo" / "manifest.json"


def simulate_whatsapp_compression(img: Image.Image, quality: int = 40) -> Image.Image:
    """Save and reload image as a low-quality JPEG to simulate WhatsApp."""
    import io
    buffer = io.BytesIO()
    # Convert RGBA to RGB for JPEG
    if img.mode == 'RGBA':
        background = Image.new('RGB', img.size, (255, 255, 255))
        background.paste(img, mask=img.split()[3])
        img = background
    
    img.save(buffer, format="JPEG", quality=quality)
    buffer.seek(0)
    return Image.open(buffer)


def inject_splicing_artifact(img: Image.Image, region: tuple[int, int, int, int]) -> Image.Image:
    """Simulate a clumsy copy-paste job by drawing a faint mismatched edge."""
    # A subtle bounding box indicating where the fraudster MS Paint'ed the text
    draw = ImageDraw.Draw(img)
    x1, y1, x2, y2 = region
    
    # Draw faint borders that mimic a slightly off-color background paste
    draw.rectangle([x1, y1, x2, y2], outline=(245, 245, 250), width=2)
    
    # Apply a tiny localized blur to the region edges (masking attempt)
    box = img.crop(region)
    blurred_box = box.filter(ImageFilter.GaussianBlur(radius=0.5))
    img.paste(blurred_box, region)
    
    return img


def inject_double_compression(img: Image.Image, region: tuple[int, int, int, int]) -> Image.Image:
    """Simulate editing an already-compressed JPEG and re-saving it.
    This creates localized Error Level Analysis (ELA) hotspots.
    """
    x1, y1, x2, y2 = region
    box = img.crop(region)
    
    # Compress JUST the box horribly, then paste it back
    import io
    buffer = io.BytesIO()
    box.save(buffer, format="JPEG", quality=15)
    buffer.seek(0)
    recompressed_box = Image.open(buffer)
    
    img.paste(recompressed_box, region)
    return img


def tamper_suspicious_case(img: Image.Image, case_id: str, tamper_type: str) -> Image.Image:
    """Inject specific localized forensic artifacts based on tamper type."""
    if img.mode == "RGBA":
        img = img.convert("RGB")
        
    width, height = img.size
    
    if tamper_type == "amount_edit":
        # Amount is typically in the top third, horizontally centered-ish
        # We target a generic box in the header where the amount lives (y=500 for our 3x dpi templates)
        region = (width // 4, 380, width * 3 // 4, 520)
        img = inject_double_compression(img, region)
        img = inject_splicing_artifact(img, region)
        
    elif tamper_type == "ref_edit":
        # Reference ID is usually the first row in the details card
        region = (width // 2, 700, width - 60, 800)
        img = inject_splicing_artifact(img, region)
        
    elif tamper_type == "date_edit":
        # Date is usually the second row in the details card
        region = (width // 2, 850, width - 60, 950)
        img = inject_double_compression(img, region)
        
    elif tamper_type == "name_edit":
        # Sender/Receiver names
        region = (width // 2, 1000, width - 60, 1200)
        img = inject_splicing_artifact(img, region)
        
    elif tamper_type == "fabricated":
        # Entire image has weird noise profile
        img = simulate_whatsapp_compression(img, quality=20)
        
    elif tamper_type == "careful_edit":
        # Professional edit — leaves almost no visual trace, relies on ledger conflict
        pass 

    return img


def main():
    if not IMAGES_DIR.exists():
        print(f"Error: {IMAGES_DIR} not found. Run render_receipts.py first.")
        return

    with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    # Convert manifest back to dict for easy lookup
    cases = {c["id"]: c for c in manifest["cases"]}
    
    processed_count = 0
    tampered_count = 0

    print("Running Compression & Tamper Pipeline...\n")
    
    for png_path in sorted(IMAGES_DIR.glob("*.png")):
        case_id = png_path.stem  # e.g., 'G01'
        
        if case_id not in cases:
            continue
            
        case = cases[case_id]
        img = Image.open(png_path)
        
        # 1. If SUSPICIOUS, inject forensic traces
        if case["category"] == "SUSPICIOUS":
            tamper_type = case.get("tamper_type", "careful_edit")
            img = tamper_suspicious_case(img, case_id, tamper_type)
            tampered_count += 1
            print(f"  [TAMPER] {case_id}: Injected {tamper_type} artifacts")

        # 2. Convert ALL to JPEG (WhatsApp compression)
        # Using typical WhatsApp quality (around 40-50)
        img_jpg = simulate_whatsapp_compression(img, quality=45)
        
        # 3. Save as .jpg, delete the perfect .png
        jpg_path = png_path.with_suffix(".jpg")
        img_jpg.save(jpg_path, format="JPEG")
        png_path.unlink()
        
        processed_count += 1

    print(f"\n✓ Processed {processed_count} images (Converted pristine PNGs → compressed JPGs)")
    print(f"✓ Injected forensic traces into {tampered_count} SUSPICIOUS images")


if __name__ == "__main__":
    main()
