"""create initial proofpay schema

Revision ID: 39c60d9844b6
Revises:
Create Date: 2026-08-24 12:54:10.276293
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "39c60d9844b6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("default_currency", sa.String(length=3), nullable=False),
        sa.Column("default_timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "SUSPENDED",
                "CLOSED",
                name="merchantstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "SUSPENDED",
                "DISABLED",
                name="userstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "branches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "INACTIVE", name="branchstatus", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_branches_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_branches")),
        sa.UniqueConstraint("merchant_id", "code", name="uq_branch_merchant_code"),
        sa.UniqueConstraint("merchant_id", "id", name="uq_branch_merchant_id"),
    )
    with op.batch_alter_table("branches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_branches_merchant_id"), ["merchant_id"], unique=False)

    op.create_table(
        "merchant_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "MERCHANT_ADMIN",
                "MANAGER",
                "VERIFIER",
                "REVIEWER",
                name="membershiprole",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "scope_mode",
            sa.Enum(
                "MERCHANT_WIDE",
                "BRANCHES",
                "ASSIGNED_RESOURCES",
                name="membershipscope",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "INVITED",
                "ACTIVE",
                "SUSPENDED",
                "REVOKED",
                name="membershipstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("invited_by_membership_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "invited_by_membership_id"],
            ["merchant_memberships.merchant_id", "merchant_memberships.id"],
            name="fk_membership_invited_by_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_merchant_memberships_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_merchant_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchant_memberships")),
        sa.UniqueConstraint("merchant_id", "id", name="uq_membership_merchant_id"),
        sa.UniqueConstraint("merchant_id", "user_id", name="uq_membership_merchant_user"),
    )
    with op.batch_alter_table("merchant_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_merchant_memberships_merchant_id"), ["merchant_id"], unique=False
        )

    op.create_table(
        "payment_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("provider_code", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("masked_account_ref", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "DISABLED",
                name="paymentaccountstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_payment_accounts_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_accounts")),
        sa.UniqueConstraint("merchant_id", "id", name="uq_payment_account_merchant_id"),
    )
    with op.batch_alter_table("payment_accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payment_accounts_merchant_id"), ["merchant_id"], unique=False
        )
        batch_op.create_index(
            "ix_payment_accounts_merchant_provider", ["merchant_id", "provider_code"], unique=False
        )

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("actor_membership_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=128), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("ip_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "actor_membership_id"],
            ["merchant_memberships.merchant_id", "merchant_memberships.id"],
            name="fk_audit_actor_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_audit_events_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_audit_events_merchant_created", ["merchant_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_merchant_id"), ["merchant_id"], unique=False
        )
        batch_op.create_index(
            "ix_audit_events_merchant_resource",
            ["merchant_id", "resource_type", "resource_id"],
            unique=False,
        )

    op.create_table(
        "branch_memberships",
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "branch_id"],
            ["branches.merchant_id", "branches.id"],
            name="fk_branch_membership_branch_same_merchant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "membership_id"],
            ["merchant_memberships.merchant_id", "merchant_memberships.id"],
            name="fk_branch_membership_membership_same_merchant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_branch_memberships_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("branch_id", "membership_id", name=op.f("pk_branch_memberships")),
    )
    with op.batch_alter_table("branch_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_branch_memberships_merchant_id"), ["merchant_id"], unique=False
        )
        batch_op.create_index(
            "ix_branch_memberships_merchant_membership",
            ["merchant_id", "membership_id"],
            unique=False,
        )

    op.create_table(
        "merchant_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("payment_account_id", sa.Uuid(), nullable=False),
        sa.Column("provider_code", sa.String(length=64), nullable=False),
        sa.Column("external_transaction_id", sa.String(length=255), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("sender_name", sa.String(length=255), nullable=True),
        sa.Column("sender_reference", sa.String(length=128), nullable=True),
        sa.Column("receiver_name", sa.String(length=255), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "POSTED",
                "PENDING",
                "REVERSED",
                name="transactionstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "source_type",
            sa.Enum(
                "PROVIDER",
                "WEBHOOK",
                "CSV",
                "MANUAL",
                "DEMO",
                name="transactionsourcetype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "trust_level",
            sa.Enum(
                "TRUSTED",
                "PARTIAL",
                "DEMO_TRUSTED",
                name="transactiontrustlevel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "source_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_minor >= 0",
            name=op.f("ck_merchant_transactions_transaction_amount_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "payment_account_id"],
            ["payment_accounts.merchant_id", "payment_accounts.id"],
            name="fk_transaction_account_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_merchant_transactions_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchant_transactions")),
        sa.UniqueConstraint("merchant_id", "id", name="uq_transaction_merchant_id"),
        sa.UniqueConstraint(
            "merchant_id",
            "provider_code",
            "payment_account_id",
            "external_transaction_id",
            name="uq_transaction_merchant_provider_external",
        ),
    )
    with op.batch_alter_table("merchant_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_merchant_transactions_merchant_id"), ["merchant_id"], unique=False
        )
        batch_op.create_index(
            "ix_transactions_merchant_account_status_occurred",
            ["merchant_id", "payment_account_id", "status", "occurred_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_transactions_merchant_provider_occurred",
            ["merchant_id", "provider_code", "occurred_at"],
            unique=False,
        )

    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("external_order_ref", sa.String(length=255), nullable=True),
        sa.Column("customer_reference", sa.String(length=255), nullable=True),
        sa.Column("expected_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_PAYMENT",
                "PAYMENT_REVIEW",
                "PAID",
                "CANCELLED",
                name="orderstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("assigned_verifier_membership_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expected_amount_minor >= 0", name=op.f("ck_orders_order_amount_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "assigned_verifier_membership_id"],
            ["merchant_memberships.merchant_id", "merchant_memberships.id"],
            name="fk_order_verifier_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "branch_id"],
            ["branches.merchant_id", "branches.id"],
            name="fk_order_branch_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_orders_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("merchant_id", "external_order_ref", name="uq_order_merchant_ref"),
        sa.UniqueConstraint("merchant_id", "id", name="uq_order_merchant_id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(
            "ix_orders_merchant_assignee_status",
            ["merchant_id", "assigned_verifier_membership_id", "status"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_orders_merchant_id"), ["merchant_id"], unique=False)

    op.create_table(
        "payment_proofs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("width_px", sa.Integer(), nullable=False),
        sa.Column("height_px", sa.Integer(), nullable=False),
        sa.Column("sha256_hash", sa.String(length=64), nullable=False),
        sa.Column("perceptual_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "retention_status",
            sa.Enum(
                "ACTIVE",
                "PENDING_DELETE",
                "DELETED",
                name="proofretentionstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["merchant_id", "uploaded_by_membership_id"],
            ["merchant_memberships.merchant_id", "merchant_memberships.id"],
            name="fk_proof_uploader_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_payment_proofs_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_proofs")),
        sa.UniqueConstraint("merchant_id", "id", name="uq_proof_merchant_id"),
        sa.UniqueConstraint("storage_key", name=op.f("uq_payment_proofs_storage_key")),
    )
    with op.batch_alter_table("payment_proofs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payment_proofs_merchant_id"), ["merchant_id"], unique=False
        )
        batch_op.create_index(
            "ix_proofs_merchant_sha256", ["merchant_id", "sha256_hash"], unique=True
        )
        batch_op.create_index(
            "ix_proofs_merchant_uploaded_at", ["merchant_id", "uploaded_at"], unique=False
        )

    op.create_table(
        "payment_claims",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("payment_proof_id", sa.Uuid(), nullable=False),
        sa.Column("provider_code", sa.String(length=64), nullable=True),
        sa.Column("claimed_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("sender_name", sa.String(length=255), nullable=True),
        sa.Column("receiver_name", sa.String(length=255), nullable=True),
        sa.Column("external_transaction_id", sa.String(length=255), nullable=True),
        sa.Column("claimed_occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timestamp_raw", sa.String(length=255), nullable=True),
        sa.Column("timezone_assumption", sa.String(length=64), nullable=True),
        sa.Column(
            "field_confidences",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("raw_ocr_text", sa.Text(), nullable=True),
        sa.Column("provider_template", sa.String(length=128), nullable=True),
        sa.Column("parser_version", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "payment_proof_id"],
            ["payment_proofs.merchant_id", "payment_proofs.id"],
            name="fk_claim_proof_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_payment_claims_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_claims")),
        sa.UniqueConstraint("merchant_id", "id", name="uq_claim_merchant_id"),
    )
    with op.batch_alter_table("payment_claims", schema=None) as batch_op:
        batch_op.create_index(
            "ix_claims_merchant_proof", ["merchant_id", "payment_proof_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_payment_claims_merchant_id"), ["merchant_id"], unique=False
        )

    op.create_table(
        "verification_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("payment_proof_id", sa.Uuid(), nullable=False),
        sa.Column("payment_claim_id", sa.Uuid(), nullable=True),
        sa.Column("requested_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column(
            "lifecycle_status",
            sa.Enum(
                "RECEIVED",
                "VALIDATING",
                "PROCESSING",
                "DECIDED",
                "REVIEWED",
                "FAILED",
                name="verificationlifecyclestatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "decision_status",
            sa.Enum(
                "VERIFIED",
                "UNMATCHED",
                "SUSPICIOUS",
                "DUPLICATE",
                "NEEDS_REVIEW",
                name="status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "risk_level",
            sa.Enum(
                "LOW", "MEDIUM", "HIGH", name="risk", native_enum=False, create_constraint=True
            ),
            nullable=True,
        ),
        sa.Column("decision_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("selected_transaction_id", sa.Uuid(), nullable=True),
        sa.Column("rule_set_version", sa.String(length=128), nullable=True),
        sa.Column("summary_reason_code", sa.String(length=128), nullable=True),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column("failure_detail", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "order_id"],
            ["orders.merchant_id", "orders.id"],
            name="fk_attempt_order_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "payment_claim_id"],
            ["payment_claims.merchant_id", "payment_claims.id"],
            name="fk_attempt_claim_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "payment_proof_id"],
            ["payment_proofs.merchant_id", "payment_proofs.id"],
            name="fk_attempt_proof_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "requested_by_membership_id"],
            ["merchant_memberships.merchant_id", "merchant_memberships.id"],
            name="fk_attempt_requester_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "selected_transaction_id"],
            ["merchant_transactions.merchant_id", "merchant_transactions.id"],
            name="fk_attempt_selected_transaction_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_verification_attempts_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_attempts")),
        sa.UniqueConstraint(
            "merchant_id", "id", "selected_transaction_id", name="uq_attempt_selected_transaction"
        ),
        sa.UniqueConstraint("merchant_id", "id", name="uq_attempt_merchant_id"),
    )
    with op.batch_alter_table("verification_attempts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_attempts_merchant_decision_created",
            ["merchant_id", "decision_status", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_attempts_merchant_order_created",
            ["merchant_id", "order_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_verification_attempts_merchant_id"), ["merchant_id"], unique=False
        )

    op.create_table(
        "evidence_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("verification_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_code", sa.String(length=128), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "PASS",
                "FAIL",
                "WARNING",
                "UNKNOWN",
                name="evidenceoutcome",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "observed_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "expected_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("source_component", sa.String(length=128), nullable=False),
        sa.Column("component_version", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "score IS NULL OR (score >= 0 AND score <= 1)",
            name=op.f("ck_evidence_items_evidence_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "verification_attempt_id"],
            ["verification_attempts.merchant_id", "verification_attempts.id"],
            name="fk_evidence_attempt_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_evidence_items_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_items")),
    )
    with op.batch_alter_table("evidence_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_items_merchant_id"), ["merchant_id"], unique=False
        )
        batch_op.create_index(
            "ix_evidence_merchant_attempt", ["merchant_id", "verification_attempt_id"], unique=False
        )

    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("verification_attempt_id", sa.Uuid(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "IN_PROGRESS",
                "COMPLETED",
                name="idempotencystate",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column(
            "response_body",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state = 'IN_PROGRESS' OR verification_attempt_id IS NOT NULL",
            name=op.f("ck_idempotency_records_idempotency_completed_attempt_required"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "verification_attempt_id"],
            ["verification_attempts.merchant_id", "verification_attempts.id"],
            name="fk_idempotency_attempt_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_idempotency_records_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint("merchant_id", "idempotency_key", name="uq_idempotency_merchant_key"),
    )
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.create_index("ix_idempotency_expiry", ["merchant_id", "expires_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_idempotency_records_merchant_id"), ["merchant_id"], unique=False
        )

    op.create_table(
        "manual_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("verification_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_membership_id", sa.Uuid(), nullable=False),
        sa.Column(
            "previous_decision_status",
            sa.Enum(
                "VERIFIED",
                "UNMATCHED",
                "SUSPICIOUS",
                "DUPLICATE",
                "NEEDS_REVIEW",
                name="status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "review_outcome",
            sa.Enum(
                "UPHELD",
                "OVERRIDDEN",
                "MORE_EVIDENCE_REQUIRED",
                name="reviewoutcome",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "new_decision_status",
            sa.Enum(
                "VERIFIED",
                "UNMATCHED",
                "SUSPICIOUS",
                "DUPLICATE",
                "NEEDS_REVIEW",
                name="status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(review_outcome = 'OVERRIDDEN' AND new_decision_status IS NOT NULL) OR (review_outcome <> 'OVERRIDDEN' AND new_decision_status IS NULL)",
            name=op.f("ck_manual_reviews_manual_review_override_status_consistent"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "reviewer_membership_id"],
            ["merchant_memberships.merchant_id", "merchant_memberships.id"],
            name="fk_manual_review_reviewer_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "verification_attempt_id"],
            ["verification_attempts.merchant_id", "verification_attempts.id"],
            name="fk_manual_review_attempt_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_manual_reviews_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_reviews")),
    )
    with op.batch_alter_table("manual_reviews", schema=None) as batch_op:
        batch_op.create_index(
            "ix_manual_reviews_merchant_attempt",
            ["merchant_id", "verification_attempt_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_manual_reviews_merchant_id"), ["merchant_id"], unique=False
        )

    op.create_table(
        "match_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("verification_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_transaction_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("aggregate_score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column(
            "field_scores",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "critical_conflicts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("matcher_version", sa.String(length=128), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "merchant_transaction_id"],
            ["merchant_transactions.merchant_id", "merchant_transactions.id"],
            name="fk_candidate_transaction_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "verification_attempt_id"],
            ["verification_attempts.merchant_id", "verification_attempts.id"],
            name="fk_candidate_attempt_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_match_candidates_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_candidates")),
        sa.UniqueConstraint(
            "verification_attempt_id",
            "merchant_transaction_id",
            name="uq_candidate_attempt_transaction",
        ),
        sa.UniqueConstraint("verification_attempt_id", "rank", name="uq_candidate_attempt_rank"),
    )
    with op.batch_alter_table("match_candidates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_match_candidates_merchant_id"), ["merchant_id"], unique=False
        )
        # Hand-maintained: Alembic does not reliably compare partial-index predicates.
        batch_op.create_index(
            "uq_candidate_selected_attempt",
            ["verification_attempt_id"],
            unique=True,
            sqlite_where=sa.text("selected = 1"),
            postgresql_where=sa.text("selected = true"),
        )

    op.create_table(
        "review_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("verification_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_membership_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="reviewassignmentstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["merchant_id", "reviewer_membership_id"],
            ["merchant_memberships.merchant_id", "merchant_memberships.id"],
            name="fk_review_assignment_reviewer_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "verification_attempt_id"],
            ["verification_attempts.merchant_id", "verification_attempts.id"],
            name="fk_review_assignment_attempt_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_review_assignments_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_assignments")),
    )
    with op.batch_alter_table("review_assignments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_review_assignments_merchant_id"), ["merchant_id"], unique=False
        )
        batch_op.create_index(
            "ix_review_assignments_merchant_reviewer_status",
            ["merchant_id", "reviewer_membership_id", "status"],
            unique=False,
        )
        # Hand-maintained: only one open/in-progress reviewer may own an attempt.
        batch_op.create_index(
            "uq_review_assignment_active_attempt",
            ["verification_attempt_id"],
            unique=True,
            sqlite_where=sa.text("status IN ('OPEN', 'IN_PROGRESS')"),
            postgresql_where=sa.text("status IN ('OPEN', 'IN_PROGRESS')"),
        )

    op.create_table(
        "transaction_allocations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_transaction_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("verification_attempt_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "RELEASED",
                name="allocationstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "allocated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_by_membership_id", sa.Uuid(), nullable=True),
        sa.Column("release_reason", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "(status = 'ACTIVE' AND released_at IS NULL AND released_by_membership_id IS NULL AND release_reason IS NULL) OR (status = 'RELEASED' AND released_at IS NOT NULL AND released_by_membership_id IS NOT NULL AND release_reason IS NOT NULL)",
            name=op.f("ck_transaction_allocations_allocation_release_fields_consistent"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "merchant_transaction_id"],
            ["merchant_transactions.merchant_id", "merchant_transactions.id"],
            name="fk_allocation_transaction_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "order_id"],
            ["orders.merchant_id", "orders.id"],
            name="fk_allocation_order_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "released_by_membership_id"],
            ["merchant_memberships.merchant_id", "merchant_memberships.id"],
            name="fk_allocation_releaser_same_merchant",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "verification_attempt_id", "merchant_transaction_id"],
            [
                "verification_attempts.merchant_id",
                "verification_attempts.id",
                "verification_attempts.selected_transaction_id",
            ],
            name="fk_allocation_selected_transaction",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_transaction_allocations_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transaction_allocations")),
    )
    with op.batch_alter_table("transaction_allocations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_allocations_merchant_order_status",
            ["merchant_id", "order_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_transaction_allocations_merchant_id"), ["merchant_id"], unique=False
        )
        # Hand-maintained: released allocations must not block later correction.
        batch_op.create_index(
            "uq_allocation_active_order",
            ["order_id"],
            unique=True,
            sqlite_where=sa.text("status = 'ACTIVE'"),
            postgresql_where=sa.text("status = 'ACTIVE'"),
        )
        batch_op.create_index(
            "uq_allocation_active_txn",
            ["merchant_transaction_id"],
            unique=True,
            sqlite_where=sa.text("status = 'ACTIVE'"),
            postgresql_where=sa.text("status = 'ACTIVE'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction_allocations", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_allocation_active_txn",
            sqlite_where=sa.text("status = 'ACTIVE'"),
            postgresql_where=sa.text("status = 'ACTIVE'"),
        )
        batch_op.drop_index(
            "uq_allocation_active_order",
            sqlite_where=sa.text("status = 'ACTIVE'"),
            postgresql_where=sa.text("status = 'ACTIVE'"),
        )
        batch_op.drop_index(batch_op.f("ix_transaction_allocations_merchant_id"))
        batch_op.drop_index("ix_allocations_merchant_order_status")

    op.drop_table("transaction_allocations")
    with op.batch_alter_table("review_assignments", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_review_assignment_active_attempt",
            sqlite_where=sa.text("status IN ('OPEN', 'IN_PROGRESS')"),
            postgresql_where=sa.text("status IN ('OPEN', 'IN_PROGRESS')"),
        )
        batch_op.drop_index("ix_review_assignments_merchant_reviewer_status")
        batch_op.drop_index(batch_op.f("ix_review_assignments_merchant_id"))

    op.drop_table("review_assignments")
    with op.batch_alter_table("match_candidates", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_candidate_selected_attempt",
            sqlite_where=sa.text("selected = 1"),
            postgresql_where=sa.text("selected = true"),
        )
        batch_op.drop_index(batch_op.f("ix_match_candidates_merchant_id"))

    op.drop_table("match_candidates")
    with op.batch_alter_table("manual_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_manual_reviews_merchant_id"))
        batch_op.drop_index("ix_manual_reviews_merchant_attempt")

    op.drop_table("manual_reviews")
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_idempotency_records_merchant_id"))
        batch_op.drop_index("ix_idempotency_expiry")

    op.drop_table("idempotency_records")
    with op.batch_alter_table("evidence_items", schema=None) as batch_op:
        batch_op.drop_index("ix_evidence_merchant_attempt")
        batch_op.drop_index(batch_op.f("ix_evidence_items_merchant_id"))

    op.drop_table("evidence_items")
    with op.batch_alter_table("verification_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_verification_attempts_merchant_id"))
        batch_op.drop_index("ix_attempts_merchant_order_created")
        batch_op.drop_index("ix_attempts_merchant_decision_created")

    op.drop_table("verification_attempts")
    with op.batch_alter_table("payment_claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_claims_merchant_id"))
        batch_op.drop_index("ix_claims_merchant_proof")

    op.drop_table("payment_claims")
    with op.batch_alter_table("payment_proofs", schema=None) as batch_op:
        batch_op.drop_index("ix_proofs_merchant_uploaded_at")
        batch_op.drop_index("ix_proofs_merchant_sha256")
        batch_op.drop_index(batch_op.f("ix_payment_proofs_merchant_id"))

    op.drop_table("payment_proofs")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_merchant_id"))
        batch_op.drop_index("ix_orders_merchant_assignee_status")

    op.drop_table("orders")
    with op.batch_alter_table("merchant_transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_transactions_merchant_provider_occurred")
        batch_op.drop_index("ix_transactions_merchant_account_status_occurred")
        batch_op.drop_index(batch_op.f("ix_merchant_transactions_merchant_id"))

    op.drop_table("merchant_transactions")
    with op.batch_alter_table("branch_memberships", schema=None) as batch_op:
        batch_op.drop_index("ix_branch_memberships_merchant_membership")
        batch_op.drop_index(batch_op.f("ix_branch_memberships_merchant_id"))

    op.drop_table("branch_memberships")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_events_merchant_resource")
        batch_op.drop_index(batch_op.f("ix_audit_events_merchant_id"))
        batch_op.drop_index("ix_audit_events_merchant_created")

    op.drop_table("audit_events")
    with op.batch_alter_table("payment_accounts", schema=None) as batch_op:
        batch_op.drop_index("ix_payment_accounts_merchant_provider")
        batch_op.drop_index(batch_op.f("ix_payment_accounts_merchant_id"))

    op.drop_table("payment_accounts")
    with op.batch_alter_table("merchant_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_merchant_memberships_merchant_id"))

    op.drop_table("merchant_memberships")
    with op.batch_alter_table("branches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_branches_merchant_id"))

    op.drop_table("branches")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("merchants")
    # ### end Alembic commands ###
